language: node_js
node_js: '6.9.4'
sudo: false
os: linux
dist: trusty

branches:
  only:
  - master

matrix:
  include:
  - env:
    - ATOM_CHANNEL=stable
    addons:
      apt:
        packages:
        - clang-3.3
        - build-essential
        - gnome-keyring
        - libsecret-1-dev
        - python-gnomekeyring
  - env:
    - ATOM_CHANNEL=beta
    addons:
      apt:
        packages:
        - clang-3.3
        - build-essential
        - gnome-keyring
        - libsecret-1-dev
        - python-gnomekeyring

env:
  global:
  - secure: "er/MMyeHzgvBiMObPn/h9rIgf/8pKLjtMB3sTywIO3KPsfcoGh6SPMz+jOpJBzbCQ+si660AHgWzko/t4WJIfZ7BBmn+35dcy6k8dWkZ6dP+WqLPjmuDQ/O1uv8xi4enwg3r0MeFBTXsd0QAW05kA9HJ9oHzZKjM3B67uuRmFwI1QsDJqMtLCgvDJ3hHpem/lccf5iDLtDR8orbaWuYy7T0irID2yFRXyYzPOY/w7sy4pQTGMA4YlBkQSEJ6yQTHrRXo6BxR0KvOcNZNy/SiGk4BXICU3h8NiSjmPLtvbH4MptpiQ7MZgGBGBB71NGGwZNoyIIJiPGHDYHjdtek/JyTI74X87Wqx9obTSkusBCylIcrWc2RjKcMcS9sYojJhgiZjsvrkbv03Ti3/yAhe62Y5Ca7ok4e68dEUG23yQm47oOENuHdW9tx35lYoHrQqQc0pbpYfKxlRsOA9fJtvn0fjcM5ZKyja3ABPwVgchx7erpd0tyPPuUDQOkWQlkIGzmthk1JLtaoCVJkUjX8MrRIBrPB2h0EUPgh3AbIl2P7CTJdsUKvSaTpgzONmIXA4xAjWGmwCLWyRC/FWJeeKg9LItwUXMwyLM+0CPX7C0MBQWgxKBFohAaBWwU1QY71KEGYYnDQLt75Qh1aF/u/SGGZxBE+Hp9+3+Jt5fOYgiiU="
  - npm_config_clang=1
  - CC=clang
  - CXX=clang++
  - ATOM_GITHUB_FS_EVENT_LOG=1
  - MOCHA_TIMEOUT=60000
  - UNTIL_TIMEOUT=30000
  - TRAVIS_BUILD_JOB=runtests
  matrix:
  - ATOM_CHANNEL=stable
  - ATOM_CHANNEL=beta

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "cm17gjkIkp4cGPy5PTolNJlCGecqU0VptbEvv1HjqkrOnwPJibK9H8DVjmN4Xx3HTRPjlRIEOE/CmadFcJ0+jIsvId47AnrEOOWVQwAEWNpxDWd0zvVr0/TdKOm+9pPFo16I/1OtLT8keCs0WyoVfzC+p56dhSw+KR8I+0Zbwv/BVH/BYn3LsiCzNS/vp4bajcqLmq+23hderskpEHaX9HpbhYNy6nm3haZBYimvdSKkQdW7eSmwU5JZ6hdhUH5sqmIq5mRV1jppREQ86UF0CupSmZGPtvRK/EGEiCETB5vD7aSx9kPaxQ5P5YNG+Kq5mHNzj/k0ZrhMjdH6xoeSMjdW3Hn0gqc/zhy0qY/LeBSwVJFFq8Xy2K1SIDKYX/X5Jmo/ZIrJmN+p45+JHY5gxmtu1ckteeFtKpJye4WPmeYAGpmJDTgtLdGV6XWZGWXdMTBbOGcLsNtZrx5aCueuhiiOb6zFgydhMR63WBharkz39ABQIA3RVHwPmpe+HhJbM4+eijA2WPbTJxFxjBw+mwlakag0RfuERutRjmUI++JBdbB7xzEet1Cfyk1p833xYG3YlXZV+BHUzt6/0OFaIQYcqpryjtFS10GVQbeFdNbxhNig6MKQ8cirpra6JQafRUuTmBAxIP/ZmglF8h0ZwT8lMnNgTHa/QhdALmVNYBk="

install:
- npm install -g npm
- 'if [ "${TRAVIS_BUILD_JOB}" = "schemacheck" ] && [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install jq; fi'

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start); fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      dbus-launch /usr/bin/python -c \
        "import gnomekeyring;gnomekeyring.create_sync('login', '');"
    fi

script:
- ./script/cibuild
