language: objective-c

env:
  - ATOM_CHANNEL=beta

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install 4.4.7
  - nvm use --delete-prefix 4.4.7
  - npm install -g npm

script:
  - ./script/cibuild
