parameters:
  atom_channel: dev
  atom_name: atom-dev

steps:
- bash: |
    if [ -n "${SSH_PRIVATEKEY}" ]; then
      mkdir -p ${HOME}/.ssh/
      chmod 700 ${HOME}/.ssh/
      echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ${HOME}/.ssh/known_hosts
      echo "${SSH_PRIVATEKEY}" > ${HOME}/.ssh/id_rsa;
    fi
    curl -s -L "https://atom.io/download/deb?channel=${ATOM_CHANNEL}" \
      -H 'Accept: application/octet-stream' \
      -o 'atom-amd64.deb'
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
    sudo apt-get update && sudo apt-get install -yyq libgconf-2-4 build-essential git libsecret-1-dev
    dpkg-deb -x atom-amd64.deb /tmp/atom
  displayName: install Atom
  env:
    ATOM_CHANNEL: ${{ parameters.atom_channel }}
    SSH_PRIVATEKEY: $(ssh.privateKey)
- bash: |
    "/tmp/atom/usr/share/${ATOM_NAME}/resources/app/apm/bin/apm" ci
  displayName: install dependencies
  env:
    ATOM_NAME: ${{ parameters.atom_name }}
